name: Pipeline for Product Management API

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
      - name: Run Unit Tests
        run: ./gradlew test --tests live.stoicism.productsampleapi.unit.ProductControllerTest
      - name: Run Integration Tests
        run: ./gradlew test --tests live.stoicism.productsampleapi.integration.ProductControllerIntegrationTest
      - name: Run Cucumber Acceptance Tests
        run: ./gradlew test --tests live.stoicism.productsampleapi.bdd.RunCucumberTest
      - name: Build and package the jar file
        run: ./gradlew build -x test
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: tnanhd/sampleapi:latest